// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: gameProto.proto

package gameProto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClientPingC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientPingC2S) Reset() {
	*x = ClientPingC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPingC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPingC2S) ProtoMessage() {}

func (x *ClientPingC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPingC2S.ProtoReflect.Descriptor instead.
func (*ClientPingC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{0}
}

type ClientLoginC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RId   *uint64 `protobuf:"varint,1,req,name=RId" json:"RId,omitempty"`
	RName *string `protobuf:"bytes,2,req,name=RName" json:"RName,omitempty"`
}

func (x *ClientLoginC2S) Reset() {
	*x = ClientLoginC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLoginC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLoginC2S) ProtoMessage() {}

func (x *ClientLoginC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLoginC2S.ProtoReflect.Descriptor instead.
func (*ClientLoginC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{1}
}

func (x *ClientLoginC2S) GetRId() uint64 {
	if x != nil && x.RId != nil {
		return *x.RId
	}
	return 0
}

func (x *ClientLoginC2S) GetRName() string {
	if x != nil && x.RName != nil {
		return *x.RName
	}
	return ""
}

type ClientLoginS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RId   *uint64 `protobuf:"varint,1,req,name=RId" json:"RId,omitempty"`
	RName *string `protobuf:"bytes,2,req,name=RName" json:"RName,omitempty"`
	Token *string `protobuf:"bytes,3,req,name=Token" json:"Token,omitempty"`
	Error *uint64 `protobuf:"varint,4,req,name=Error" json:"Error,omitempty"`
}

func (x *ClientLoginS2C) Reset() {
	*x = ClientLoginS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLoginS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLoginS2C) ProtoMessage() {}

func (x *ClientLoginS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLoginS2C.ProtoReflect.Descriptor instead.
func (*ClientLoginS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{2}
}

func (x *ClientLoginS2C) GetRId() uint64 {
	if x != nil && x.RId != nil {
		return *x.RId
	}
	return 0
}

func (x *ClientLoginS2C) GetRName() string {
	if x != nil && x.RName != nil {
		return *x.RName
	}
	return ""
}

func (x *ClientLoginS2C) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *ClientLoginS2C) GetError() uint64 {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return 0
}

//加入聊天C2S(2001)
type ClientChatJoinC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RId *uint64 `protobuf:"varint,1,req,name=RId" json:"RId,omitempty"`
}

func (x *ClientChatJoinC2S) Reset() {
	*x = ClientChatJoinC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatJoinC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatJoinC2S) ProtoMessage() {}

func (x *ClientChatJoinC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatJoinC2S.ProtoReflect.Descriptor instead.
func (*ClientChatJoinC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{3}
}

func (x *ClientChatJoinC2S) GetRId() uint64 {
	if x != nil && x.RId != nil {
		return *x.RId
	}
	return 0
}

//加入聊天S2C(2002)
type ClientChatJoinS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientChatJoinS2C) Reset() {
	*x = ClientChatJoinS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatJoinS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatJoinS2C) ProtoMessage() {}

func (x *ClientChatJoinS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatJoinS2C.ProtoReflect.Descriptor instead.
func (*ClientChatJoinS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{4}
}

//聊天消息C2S(2003)
type ClientChatC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *string `protobuf:"bytes,1,req,name=Msg" json:"Msg,omitempty"`
}

func (x *ClientChatC2S) Reset() {
	*x = ClientChatC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatC2S) ProtoMessage() {}

func (x *ClientChatC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatC2S.ProtoReflect.Descriptor instead.
func (*ClientChatC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{5}
}

func (x *ClientChatC2S) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

//聊天消息S2C(2004)
type ClientChatS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpeakerId   *uint64 `protobuf:"varint,1,req,name=speakerId" json:"speakerId,omitempty"`
	SpeakerName *string `protobuf:"bytes,2,req,name=speakerName" json:"speakerName,omitempty"`
	SpeakerText *string `protobuf:"bytes,3,req,name=speakerText" json:"speakerText,omitempty"`
}

func (x *ClientChatS2C) Reset() {
	*x = ClientChatS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatS2C) ProtoMessage() {}

func (x *ClientChatS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatS2C.ProtoReflect.Descriptor instead.
func (*ClientChatS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{6}
}

func (x *ClientChatS2C) GetSpeakerId() uint64 {
	if x != nil && x.SpeakerId != nil {
		return *x.SpeakerId
	}
	return 0
}

func (x *ClientChatS2C) GetSpeakerName() string {
	if x != nil && x.SpeakerName != nil {
		return *x.SpeakerName
	}
	return ""
}

func (x *ClientChatS2C) GetSpeakerText() string {
	if x != nil && x.SpeakerText != nil {
		return *x.SpeakerText
	}
	return ""
}

//聊天历史S2C(2005)
type ClientChatHistoryS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpeakerId   []uint64 `protobuf:"varint,1,rep,name=speakerId" json:"speakerId,omitempty"`
	SpeakerName []string `protobuf:"bytes,2,rep,name=speakerName" json:"speakerName,omitempty"`
	SpeakerText []string `protobuf:"bytes,3,rep,name=speakerText" json:"speakerText,omitempty"`
	Time        []string `protobuf:"bytes,4,rep,name=time" json:"time,omitempty"`
}

func (x *ClientChatHistoryS2C) Reset() {
	*x = ClientChatHistoryS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatHistoryS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatHistoryS2C) ProtoMessage() {}

func (x *ClientChatHistoryS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatHistoryS2C.ProtoReflect.Descriptor instead.
func (*ClientChatHistoryS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{7}
}

func (x *ClientChatHistoryS2C) GetSpeakerId() []uint64 {
	if x != nil {
		return x.SpeakerId
	}
	return nil
}

func (x *ClientChatHistoryS2C) GetSpeakerName() []string {
	if x != nil {
		return x.SpeakerName
	}
	return nil
}

func (x *ClientChatHistoryS2C) GetSpeakerText() []string {
	if x != nil {
		return x.SpeakerText
	}
	return nil
}

func (x *ClientChatHistoryS2C) GetTime() []string {
	if x != nil {
		return x.Time
	}
	return nil
}

//聊天popular(2006)
type ClientChatPopularC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N *uint32 `protobuf:"varint,1,req,name=n" json:"n,omitempty"`
}

func (x *ClientChatPopularC2S) Reset() {
	*x = ClientChatPopularC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatPopularC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatPopularC2S) ProtoMessage() {}

func (x *ClientChatPopularC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatPopularC2S.ProtoReflect.Descriptor instead.
func (*ClientChatPopularC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{8}
}

func (x *ClientChatPopularC2S) GetN() uint32 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

//聊天popular(2007)
type ClientChatPopularS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	World *string `protobuf:"bytes,1,req,name=world" json:"world,omitempty"`
}

func (x *ClientChatPopularS2C) Reset() {
	*x = ClientChatPopularS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatPopularS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatPopularS2C) ProtoMessage() {}

func (x *ClientChatPopularS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatPopularS2C.ProtoReflect.Descriptor instead.
func (*ClientChatPopularS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{9}
}

func (x *ClientChatPopularS2C) GetWorld() string {
	if x != nil && x.World != nil {
		return *x.World
	}
	return ""
}

//聊天popular(2008)
type ClientChatStatsC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rname *string `protobuf:"bytes,1,req,name=rname" json:"rname,omitempty"`
}

func (x *ClientChatStatsC2S) Reset() {
	*x = ClientChatStatsC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatStatsC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatStatsC2S) ProtoMessage() {}

func (x *ClientChatStatsC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatStatsC2S.ProtoReflect.Descriptor instead.
func (*ClientChatStatsC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{10}
}

func (x *ClientChatStatsC2S) GetRname() string {
	if x != nil && x.Rname != nil {
		return *x.Rname
	}
	return ""
}

//聊天popular(2009)
type ClientChatStatsS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rname *string `protobuf:"bytes,1,req,name=rname" json:"rname,omitempty"`
	Time  *string `protobuf:"bytes,2,req,name=time" json:"time,omitempty"`
}

func (x *ClientChatStatsS2C) Reset() {
	*x = ClientChatStatsS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatStatsS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatStatsS2C) ProtoMessage() {}

func (x *ClientChatStatsS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatStatsS2C.ProtoReflect.Descriptor instead.
func (*ClientChatStatsS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{11}
}

func (x *ClientChatStatsS2C) GetRname() string {
	if x != nil && x.Rname != nil {
		return *x.Rname
	}
	return ""
}

func (x *ClientChatStatsS2C) GetTime() string {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return ""
}

var File_gameProto_proto protoreflect.FileDescriptor

var file_gameProto_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x69, 0x6e, 0x67,
	0x5f, 0x63, 0x32, 0x73, 0x22, 0x3a, 0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x63, 0x32, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x03, 0x52, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x52, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x66, 0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x73, 0x32, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x04, 0x52, 0x03, 0x52, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x52, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28,
	0x04, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x27, 0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x5f, 0x63, 0x32, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x52, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x03, 0x52, 0x49,
	0x64, 0x22, 0x15, 0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74,
	0x4a, 0x6f, 0x69, 0x6e, 0x5f, 0x73, 0x32, 0x63, 0x22, 0x23, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x63, 0x32, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x73, 0x0a,
	0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x32, 0x63,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x04, 0x52, 0x09, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x54, 0x65,
	0x78, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x16, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68,
	0x61, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x32, 0x63, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x09, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x16, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68,
	0x61, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x5f, 0x63, 0x32, 0x73, 0x12, 0x0c, 0x0a,
	0x01, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x01, 0x6e, 0x22, 0x2e, 0x0a, 0x16, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x5f, 0x73, 0x32, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x2c, 0x0a, 0x14, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x5f,
	0x63, 0x32, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x14, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x73, 0x32,
	0x63, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
}

var (
	file_gameProto_proto_rawDescOnce sync.Once
	file_gameProto_proto_rawDescData = file_gameProto_proto_rawDesc
)

func file_gameProto_proto_rawDescGZIP() []byte {
	file_gameProto_proto_rawDescOnce.Do(func() {
		file_gameProto_proto_rawDescData = protoimpl.X.CompressGZIP(file_gameProto_proto_rawDescData)
	})
	return file_gameProto_proto_rawDescData
}

var file_gameProto_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gameProto_proto_goTypes = []interface{}{
	(*ClientPingC2S)(nil),        // 0: client_ping_c2s
	(*ClientLoginC2S)(nil),       // 1: client_login_c2s
	(*ClientLoginS2C)(nil),       // 2: client_login_s2c
	(*ClientChatJoinC2S)(nil),    // 3: client_chatJoin_c2s
	(*ClientChatJoinS2C)(nil),    // 4: client_chatJoin_s2c
	(*ClientChatC2S)(nil),        // 5: client_chat_c2s
	(*ClientChatS2C)(nil),        // 6: client_chat_s2c
	(*ClientChatHistoryS2C)(nil), // 7: client_chatHistory_s2c
	(*ClientChatPopularC2S)(nil), // 8: client_chatPopular_c2s
	(*ClientChatPopularS2C)(nil), // 9: client_chatPopular_s2c
	(*ClientChatStatsC2S)(nil),   // 10: client_chatStats_c2s
	(*ClientChatStatsS2C)(nil),   // 11: client_chatStats_s2c
}
var file_gameProto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gameProto_proto_init() }
func file_gameProto_proto_init() {
	if File_gameProto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gameProto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPingC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLoginC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLoginS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatJoinC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatJoinS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatHistoryS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatPopularC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatPopularS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatStatsC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatStatsS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gameProto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gameProto_proto_goTypes,
		DependencyIndexes: file_gameProto_proto_depIdxs,
		MessageInfos:      file_gameProto_proto_msgTypes,
	}.Build()
	File_gameProto_proto = out.File
	file_gameProto_proto_rawDesc = nil
	file_gameProto_proto_goTypes = nil
	file_gameProto_proto_depIdxs = nil
}
